version: '3.7'
services:
    db:
        container_name: vds_db
        image:  kartoza/postgis
        volumes:
            - vds_client_db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASS=password123
            - POSTGRES_USER=vdsclient
            - POSTGRES_DBNAME=vdsca
            - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432

volumes:
    vds_client_db: {}