version: '2'
services:
    db:
        container_name: vds_db
        image: postgres:9.5
        volumes:
            - vds_client_db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=password123
            - POSTGRES_USER=vdsclient
            - POSTGRES_DB=vdsca
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432

volumes:
    vds_client_db: {}